services:

    gupek.logic.base:
        abstract: true
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setFormFactory, ["@form.factory"]]
            - [setRouter, ["@router"]]

    gupek.logic.meeting:
        class:      MDurys\GupekBundle\Logic\MeetingLogic
        parent:     gupek.logic.base
        arguments:
            - @gupek.repository.meeting
            - @gupek.repository.meeting_user

    gupek.logic.bout:
        class:      MDurys\GupekBundle\Logic\BoutLogic
        parent:     gupek.logic.base

    gupek.repository.meeting:
        class: MDurys\GupekBundle\Entity\MeetingRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MDurys\GupekBundle\Entity\Meeting

    gupek.repository.meeting_user:
        class: MDurys\GupekBundle\Entity\MeetingUserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MDurys\GupekBundle\Entity\MeetingUser
