language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - mysql

before_script:
  - mysql -e 'create database gupek;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test
