<?php

namespace MDurys\GupekBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MDurys\GupekBundle\Entity\Meeting;
use MDurys\GupekBundle\Entity\User;

/**
 * MeetingUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingUserRepository extends EntityRepository
{
    /**
     * Select all MeetingUser records matching given meeting and user
     * combination.
     *
     * @param \MDurys\GupekBundle\Entity\Meeting|int $meeting
     * @param \MDurys\GupekBundle\Entity\User|int $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryByMeetingAndUser($meeting, $user)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('mu')
            ->from($this->getEntityName(), 'mu')
            ->where('mu.meeting = :meeting')
            ->andWhere('mu.user = :user')
            ->setParameter('meeting', $meeting)
            ->setParameter('user', $user);
    }

    /**
     * Get all MeetingUser records matching given meeting and user
     * combination.
     *
     * @param \MDurys\GupekBundle\Entity\Meeting|int $meeting
     * @param \MDurys\GupekBundle\Entity\User|int $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getByMeetingAndUser($meeting, $user)
    {
        return $this->queryByMeetingAndUser($meeting, $user)
            ->getQuery()
            ->getResult();
    }

    /**
     * Check if given user participates in given meeting.
     *
     * @param \MDurys\GupekBundle\Entity\Meeting|int $meeting
     * @param \MDurys\GupekBundle\Entity\User|int $user
     * @return bool
     */
    public function existsMeetingAndUser($meeting, $user)
    {
        return (bool)$this->queryByMeetingAndUser($meeting, $user)
            ->select('mu.id')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
