<?php

namespace MDurys\GupekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends EntityRepository
{
    /**
     * Get query builder, which selects all meetings from given season.
     *
     * @param int $seasonId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function queryBySeason($seasonId)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('m')
            ->from($this->getEntityName(), 'm')
            ->where('m.season = :season')
            ->setParameter('season', $seasonId);
    }

    public function getBySeason($seasonId)
    {
        return $this->queryBySeason($seasonId)
            ->getQuery()
            ->getResult();
    }

    public function getDetailsBySeason($seasonId)
    {
        $qb = $this->queryBySeason($seasonId);
        $qb
            ->select('m.id, m.date, COUNT(b.id) AS bouts')
            ->innerJoin('m.bouts', 'b')
            ->groupBy('m.id');

        return $qb->getQuery()->getResult();
    }
}
