<?php

namespace MDurys\GupekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    /**
     * Get basic information about given season: start date, end date and number of meetings.
     *
     * @param int $seasonId
     * @return array|null
     */
    public function getInfo($seasonId)
    {
        $qb = $this->getEntityManager()
            ->getRepository('MDurysGupekBundle:Meeting')
            ->queryBySeason($seasonId);
        return $qb
            ->select([$qb->expr()->min('m.date'), $qb->expr()->max('m.date'), $qb->expr()->count('m.id')])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
